create 'bibliotheque', 'auteur', 'livre'
put 'bibliotheque', 'vhugo', 'auteur:nom', 'Hugo'
put 'bibliotheque', 'vhugo', 'auteur:prenom', 'Victor'
put 'bibliotheque', 'vhugo', 'livre:titre', 'La légende des siècles'
put 'bibliotheque', 'vhugo', 'livre:categ', 'Poèmes'
put 'bibliotheque', 'vhugo', 'livre:date', '1855'
put 'bibliotheque', 'jverne', 'auteur:nom', 'Verne'
put 'bibliotheque', 'jverne', 'auteur:prenom', 'Jules'
put 'bibliotheque', 'jverne', 'livre:titre', 'Face au drapeau'
put 'bibliotheque', 'jverne', 'livre:categ', 'Roman'
put 'bibliotheque', 'jverne', 'livre:date', '1896'
scan 'bibliotheque'
get 'bibliotheque', 'vhugo'
put 'bibliotheque', 'vhugo', 'livre:date', '2024'
delete 'bibliotheque', 'vhugo', 'livre:categ'
scan 'bibliotheque', { FILTER => "SingleColumnValueFilter('livre', 'date', >=, 'binary:2000')" }
deleteall 'bibliotheque', 'jverne'
scan 'bibliotheque'